/home/ubuntu/venv/lib/python3.10/site-packages/scvi/_settings.py:63: UserWarning: Since v1.0.0, scvi-tools no longer uses a random seed by default. Run `scvi.settings.seed = 0` to reproduce results from previous versions.
  self.seed = seed
/home/ubuntu/venv/lib/python3.10/site-packages/scvi/_settings.py:70: UserWarning: Setting `dl_pin_memory_gpu_training` is deprecated in v1.0 and will be removed in v1.1. Please pass in `pin_memory` to the data loaders instead.
  self.dl_pin_memory_gpu_training = (
Global seed set to 0
obs_filter="tissue_general == 'heart' and is_primary_data == True"
devices='4'
batch_size='128'
max_epochs='1'
training data shape=(1559973, 60664)
{'strategy': 'ddp_find_unused_parameters_true', 'profiler': 'simple', 'callbacks': [<lightning.pytorch.callbacks.device_stats_monitor.DeviceStatsMonitor object at 0x7f351950ad70>]}
Traceback (most recent call last):
  File "/home/ubuntu/c2bb6f62173fea060764256030b59aeb/census_scvi.py", line 157, in <module>
    main()
  File "/home/ubuntu/c2bb6f62173fea060764256030b59aeb/census_scvi.py", line 147, in main
    model.train(max_epochs=int(max_epochs), accelerator="gpu", devices=int(devices), strategy="ddp_find_unused_parameters_true",
  File "/home/ubuntu/c2bb6f62173fea060764256030b59aeb/census_scvi.py", line 83, in train
    runner = self._train_runner_cls(
  File "/home/ubuntu/venv/lib/python3.10/site-packages/scvi/train/_trainrunner.py", line 76, in __init__
    accelerator, lightning_devices, device = parse_device_args(
  File "/home/ubuntu/venv/lib/python3.10/site-packages/scvi/model/_utils.py", line 103, in parse_device_args
    connector = _AcceleratorConnector(accelerator=accelerator, devices=devices)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/accelerator_connector.py", line 157, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/accelerator_connector.py", line 389, in _set_parallel_devices_and_init_accelerator
    self._devices_flag = accelerator_cls.parse_devices(self._devices_flag)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/lightning/pytorch/accelerators/cuda.py", line 81, in parse_devices
    return _parse_gpu_ids(devices, include_cuda=True)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/lightning/fabric/utilities/device_parser.py", line 102, in _parse_gpu_ids
    return _sanitize_gpu_ids(gpus, include_cuda=include_cuda, include_mps=include_mps)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/lightning/fabric/utilities/device_parser.py", line 134, in _sanitize_gpu_ids
    raise MisconfigurationException(
lightning.fabric.utilities.exceptions.MisconfigurationException: You requested gpu: [0, 1, 2, 3]
 But your machine only has: [0]
Command exited with non-zero status 1
	Command being timed: "python census_scvi.py tissue_general == 'heart' and is_primary_data == True 4 128 1"
	User time (seconds): 11.32
	System time (seconds): 6.05
	Percent of CPU this job got: 249%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:06.96
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1670532
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 946
	Minor (reclaiming a frame) page faults: 723435
	Voluntary context switches: 70885
	Involuntary context switches: 123
	Swaps: 0
	File system inputs: 138168
	File system outputs: 40
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
